// Single icon set — lucide-react. This module re-exports the icons the app
// actually uses, plus preserves a small set of `Icon*` aliases so earlier
// imports continue to compile while the rest of the codebase is migrated.

export {
  Play,
  Pause,
  SkipBack,
  SkipForward,
  Shuffle,
  Repeat,
  Repeat1,
  Search,
  Home,
  Library,
  ListMusic,
  X,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  MoreHorizontal,
  Heart,
  Plus,
  Sun,
  Moon,
  Volume2,
  VolumeX,
  Volume1,
  Sliders,
  SlidersHorizontal,
  Download,
  Maximize2,
  Minimize2,
  Monitor,
  User,
  Disc3,
  Music2,
  Music4,
  Loader2,
  BadgeCheck,
  Settings2,
  Waves,
} from 'lucide-react';

// Back-compat aliases matching the names used in earlier revisions of the UI.
export {
  Play as IconPlay,
  Pause as IconPause,
  SkipBack as IconPrev,
  SkipForward as IconNext,
  Shuffle as IconShuffle,
  Repeat as IconRepeat,
  Search as IconSearch,
  Home as IconHome,
  Library as IconLibrary,
  X as IconClose,
  ChevronDown as IconChevronDown,
  MoreHorizontal as IconMore,
  Heart as IconHeart,
  Plus as IconPlus,
  Sun as IconSun,
  Moon as IconMoon,
  Volume2 as IconVolume,
  SlidersHorizontal as IconSlider,
  Download as IconDownload,
  Maximize2 as IconMaximize,
} from 'lucide-react';
